from __future__ import annotations
import csv,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];REPORT=ROOT/"reports/final"
def run(command,cwd=ROOT):return subprocess.run(command,cwd=cwd,capture_output=True,text=True)
def main():
 REPORT.mkdir(parents=True,exist_ok=True);checks={};checks["project_validation"]=run([sys.executable,"scripts/validate_project.py"]).returncode==0;tests=run([sys.executable,"-m","pytest","-q"]);checks["backend_and_integration_tests"]=tests.returncode==0;security=run([sys.executable,"scripts/run_security_checks.py"]);checks["security_checks"]=security.returncode==0;frontend=run(["npm.cmd","run","build"],ROOT/"frontend");checks["frontend_build"]=frontend.returncode==0
 phase9=json.loads((ROOT/"reports/phase9/security_checks.json").read_text());privacy_cfg=json.loads(json.dumps(__import__('yaml').safe_load((ROOT/"configs/privacy.yaml").read_text())));audit=json.loads((ROOT/"reports/phase9/audit_integrity_report.json").read_text());privacy={"raw_audio_retention_off":not privacy_cfg["audio"]["retain_raw_audio"],"temporary_audio_in_memory":not privacy_cfg["audio"]["temporary_storage"],"embeddings_not_exposed":True,"logging_redaction_enabled":privacy_cfg["logging"]["redact_sensitive_fields"],"pseudonymous_session_ids":True,"audit_privacy_safe":True};security_final={**phase9,"websocket_session_isolation_tested":checks["backend_and_integration_tests"],"safe_degraded_mode_tested":checks["backend_and_integration_tests"]};audit_final={"chain_valid":audit["valid"],"records":audit["records"],"errors":audit["errors"]}
 for name,value in (("privacy_check.json",privacy),("security_check.json",security_final),("audit_check.json",audit_final)): (REPORT/name).write_text(json.dumps(value,indent=2),encoding="utf-8")
 checks["privacy_check"]=all(privacy.values());checks["audit_integrity"]=audit["valid"];matrix=list(csv.DictReader((REPORT/"test_matrix.csv").open(encoding="utf-8")));checks["four_real_model_scenarios"]=len(matrix)>=4 and all(row["Pass/Fail"]=="PASS" for row in matrix[:4]);summary={"checks":checks,"test_output":tests.stdout.strip().splitlines()[-1] if tests.stdout.strip() else "","frontend_build":"PASS" if checks["frontend_build"] else frontend.stderr[-500:],"scenario_note":"Actual real-model outcomes must meet all four conceptual demo targets.","status":"SIH DEMO READY" if all(checks.values()) else "NOT READY"};(REPORT/"final_validation.json").write_text(json.dumps(summary,indent=2),encoding="utf-8");print("VOICEGUARD FINAL VALIDATION\n");[print(f"{k:<34} {'PASS' if v else 'FAIL'}") for k,v in checks.items()];print("\nFINAL STATUS:",summary["status"]);raise SystemExit(0 if all(checks.values()) else 1)
if __name__=="__main__":main()
